on: [push]
name: build
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc:
          - '8.10.2'
          - '8.8.3'
          - '8.6.5'
          - '8.4.4'
          - '8.2.2'
          - '8.0.2'
          - '7.10.3'
        cabal: ['3.2']
        os: [ubuntu-latest]
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Haskell
        uses: actions/setup-haskell@v1.1.3
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - name: Build dependencies
        run: cabal build --enable-tests --enable-bench --dep -j all
      - name: Build ghc-events
        run: cabal build
      - name: Run tests
        run: cabal test --test-show-details=direct
      - name: Run cabal check
        run: cabal check
